<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-25T10:38:03 IST" name="Default suite" finished-at="2022-09-25T10:39:22 IST" duration-ms="79363">
    <groups>
    </groups>
    <test started-at="2022-09-25T10:38:03 IST" name="Default test" finished-at="2022-09-25T10:39:22 IST" duration-ms="79363">
      <class name="testcases.SimplelearnLoginTest">
        <test-method is-config="true" signature="DataSetUp()[pri:0, instance:testcases.SimplelearnLoginTest@441772e]" started-at="2022-09-25T10:38:03 IST" name="DataSetUp" finished-at="2022-09-25T10:38:05 IST" duration-ms="2287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataSetUp -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:testcases.SimplelearnLoginTest@441772e]" started-at="2022-09-25T10:38:05 IST" name="setup" finished-at="2022-09-25T10:38:42 IST" duration-ms="36221" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.SimplelearnLoginTest.Test1() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Test1()[pri:0, instance:testcases.SimplelearnLoginTest@441772e]" started-at="2022-09-25T10:38:42 IST" name="Test1" finished-at="2022-09-25T10:39:15 IST" duration-ms="33484" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The email or password you have entered is invalid] but found [The email or password you have entered is invalid.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.SimplelearnLoginTest.Test1(SimplelearnLoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.SimplelearnLoginTest@441772e]" started-at="2022-09-25T10:39:17 IST" name="teardown" finished-at="2022-09-25T10:39:20 IST" duration-ms="3191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="DataClean()[pri:0, instance:testcases.SimplelearnLoginTest@441772e]" started-at="2022-09-25T10:39:20 IST" name="DataClean" finished-at="2022-09-25T10:39:22 IST" duration-ms="1919" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataClean -->
      </class> <!-- testcases.SimplelearnLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
